package com.demo.pojo;

// Generated 2012-4-2 21:29:41 by Hibernate Tools 3.4.0.CR1

/**
 * Gender generated by hbm2java
 */
public class Gender implements java.io.Serializable {

	private byte id;
	private String name;

	public Gender() {
	}

	public Gender(byte id) {
		this.id = id;
	}

	public Gender(byte id, String name) {
		this.id = id;
		this.name = name;
	}

	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
